import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import { v4 as uuidv4 } from "uuid";

const server = new Server(
  {
    name: "undead-bard",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

const sessions: Record<string, any> = {};

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "bard_open_chronicle",
        description: "Open a new chronicle session for a codebase or module.",
        inputSchema: {
          type: "object",
          properties: {
            codebase_description: { type: "string" },
            chronicle_type: {
              type: "string",
              enum: ["documentation", "semantic_hunt", "release"]
            },
          },
          required: ["codebase_description", "chronicle_type"],
        },
      },
      {
        name: "bard_document_artifact",
        description: "Generate documentation for a code artifact in its language's native format.",
        inputSchema: {
          type: "object",
          properties: {
            session_id: { type: "string" },
            code: { type: "string" },
            filename: { type: "string" },
            audience: {
              type: "string",
              enum: ["developer", "architect", "stakeholder"]
            },
            adversarial_mode: { type: "boolean" },
          },
          required: ["session_id", "code", "filename", "audience"],
        },
      },
      {
        name: "bard_semantic_hunt",
        description: "Run a semantic hunt for code that matches a natural language intent description.",
        inputSchema: {
          type: "object",
          properties: {
            session_id: { type: "string" },
            query: { type: "string" },
            artifacts: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  filename: { type: "string" },
                  code: { type: "string" },
                },
                required: ["filename", "code"],
              },
            },
            threshold: { type: "number" },
          },
          required: ["session_id", "query", "artifacts"],
        },
      },
      {
        name: "bard_release_chronicle",
        description: "Generate a release chronicle from commits, PRs, or a change description.",
        inputSchema: {
          type: "object",
          properties: {
            session_id: { type: "string" },
            changes: { type: "string" },
            version: { type: "string" },
            audience: {
              type: "string",
              enum: ["developer", "architect", "stakeholder", "public", "security"]
            },
          },
          required: ["session_id", "changes", "version", "audience"],
        },
      },
    ],
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  switch (name) {
    case "bard_open_chronicle":
      const id = uuidv4();
      sessions[id] = { ...args };
      return { content: [{ type: "text", text: JSON.stringify({ session_id: id }) }] };
    case "bard_document_artifact":
      return { content: [{ type: "text", text: "Documentation generated by the Bard." }] };
    case "bard_semantic_hunt":
      return { content: [{ type: "text", text: JSON.stringify({ matches: [] }) }] };
    case "bard_release_chronicle":
      return { content: [{ type: "text", text: "# Release Chronicle" }] };
    default:
      throw new Error("Unknown tool");
  }
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch(console.error);
